### ISSUE TITLE
Dan Pollock's host file: Error 302

### ISSUE THREAD

**Issue by alleluia20** [julian-klode/dns66#293]
Since some days ago, I get the error 302 when DNS66 tries to update the Dan Pollock's host file.

I do not know whether it is temporary or permanent, but maybe you can try doing something: use a mirror (if there is one), contact Dan Pollock, etc.

Thank you.

**Comment by riQQ** [comment]
Fixed by #292

**Comment by langfingaz** [comment]
I just installed dns66 and still get the error 302 about incomplete downloaded host files. Dan Pollock's host file is missing.

Greetings,
Daniel

**Comment by Neodymium5312** [comment]
Just change the url manually to https and it will work. The next update will fix this once it's pushed

**Comment by langfingaz** [comment]
Awesome, thanks for the quick reply
